---
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bash zsh emacs23-nox
script:
  - bash -n .bashrc
  - zsh -n .zshrc
  - emacs -Q --batch -l .emacs
notifications:
  email:
    on_success: never
    on_failure: always
