---
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - bash
      # disable zsh checking on account of https://bugs.launchpad.net/ubuntu/+source/zsh/+bug/1242108
      # - zsh
      - emacs23-nox
script:
  - bash -n .bashrc
  # - zsh -n .zshrc
  - emacs -Q --batch -l .emacs
  - git config -f .gitconfig -l >/dev/null 2>&1
notifications:
  email:
    on_success: never
    on_failure: always
